server:
  port: 8080
  servlet:
    # only executable jar
    context-path: /test/
spring:
  datasource:
    # H2 in memory database (url: jdbc:h2:tcp://localhost:9090/mem:test)
    url:    jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    platform: h2
    # hikari
    type: com.zaxxer.hikari.HikariDataSource
    # see HikariConfigMXBean
    hikari:
      connection-timeout: 1000
      idle-timeout: 1000
      # maximum size that the pool is allowed to reach
      maximum-pool-size: 1
  h2:
    console:
      enabled: false

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  jackson:
    serialization:
      fail-on-empty-beans: false
          
  # liquibase setup
  liquibase:
    enabled: false
    
logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate: INFO
