/* ----- Resource ----- */
DELETE FROM RESOURCE;

INSERT INTO RESOURCE (ID, DTYPE, UUID, CREATED_BY, CREATED_ON, MODIFIED_BY, MODIFIED_ON) VALUES 
  (1 ,'data-container', random_uuid(), 'SYSTEM', sysdate, null, null),
  (2 ,'data-container', random_uuid(), 'SYSTEM', sysdate, null, null);

/* ----- Bauteillastenheft ----- */

DELETE FROM BAUTEIL_LASTENHEFT;

INSERT INTO BAUTEIL_LASTENHEFT (ID,FILE_NAME,UUID) VALUES
  (1,'doors-export1.xml', random_uuid());
  
DELETE FROM MODUSTEIL;

INSERT INTO MODUSTEIL (ID,BTLAH_ID,OBJECT_HEADING,RECORD_DATA_ID,LONG_NAME,BYTE_REIHENFOLGE) VALUES
  (1,1,'OH 1','RDID 1','LN 1','BR 1'),
  (2,1,'OH 2','RDID 2','LN 2','BR 2');
  
DELETE FROM PARAMETER;

INSERT INTO PARAMETER (ID,MT_ID,OBJECT_HEADING,LONG_NAME,SIGNAL_NAME,BIT_POSITION_START,BIT_POSITION_STOP,DEFAULTWERT) VALUES
  (1,1,'OH 1','LN 1','SN 1','1','8','1'),
  (2,2,'OH 2','LN 2','SN 2','2','8','1');
  
DELETE FROM PARAMETER_VALUE;

INSERT INTO PARAMETER_VALUE (ID,PARAM_ID,OBJECT_TEXT,MIN_WERT,MAX_WERT,LONG_NAME,AUFLOESUNG,PHYSICAL_UNIT) VALUES
  (1,1,'OT 1','1','8','LN 1','-','-'),
  (2,2,'OT 2','1','8','LN 2','-','-');

/* ----- Data Container ----- */
DELETE FROM DATA_CONTAINER;

INSERT INTO DATA_CONTAINER (ID, NAME, DESCRIPTION, TYPE, GENERATION, PART_NUMBER, DIAGNOSTIC_BUS, DIAGNOSTIC_ADDRESS, DIAGNOSTIC_KWP, TRANSPORT_PROTOCOL, BTLAH_ID) VALUES
  (1, 'DC 1', '...', 'ZDC', '2019/50', '12345678912', 'CAN', '1A2D', 'UDS', 'TP2_0', 1),
  (2, 'DC 2', '...', 'ZDC', '2019/50', '12345678912', 'CAN', '1A2D', 'UDS', 'TP2_0', 1);

/* ----- Member ----- */
DELETE FROM MEMBER;

INSERT INTO MEMBER (ID, DC_ID,ROLE_ID, USER_ID, FULL_NAME, USER_ROLE,UUID) VALUES
  (1, 1, 1, 1, 'Everton, Cliff', 'DC_SUPERVISOR', random_uuid()),
  (2, 2, 1, 1, 'Everton, Cliff', 'DC_ASSIGNEE', random_uuid());

/* ----- RESOURCE_MEMBER ----- */
DELETE FROM RESOURCE_MEMBER;

INSERT INTO RESOURCE_MEMBER (RESOURCE_ID, MEMBER_ID) VALUES
  (1, 1),
  (2, 2);
  
/* ----- Vehicle Classes ----- */
DELETE FROM VEHICLE_CLASS;

INSERT INTO VEHICLE_CLASS (ID, NAME) VALUES 
  (1, 'VC1'),
  (2, 'VC2'),
  (3, 'VC3');
  
/* ----- DATA_CONTAINER_VEHICLE_CLASS ----- */
DELETE FROM DATA_CONTAINER_VEHICLE_CLASS;

INSERT INTO DATA_CONTAINER_VEHICLE_CLASS (DATA_CONTAINER_ID, VEHICLE_CLASS_ID) VALUES
  (1, 1),
  (2, 1);  